apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: frv3jfo3u-nodejs
  janus-idp.io/tekton: frv3jfo3u-nodejs
  backstage.io/kubernetes-id: frv3jfo3u-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: frv3jfo3u-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
